/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
)

// PlacementRequestStatusApplyConfiguration represents a declarative configuration of the PlacementRequestStatus type for use
// with apply.
type PlacementRequestStatusApplyConfiguration struct {
	Result   *schedulingv1alpha2.PlacementRequestResult        `json:"result,omitempty"`
	Reason   *string                                           `json:"reason,omitempty"`
	Message  *string                                           `json:"message,omitempty"`
	Bindings []PlacementRequestBindingResultApplyConfiguration `json:"bindings,omitempty"`
}

// PlacementRequestStatusApplyConfiguration constructs a declarative configuration of the PlacementRequestStatus type for use with
// apply.
func PlacementRequestStatus() *PlacementRequestStatusApplyConfiguration {
	return &PlacementRequestStatusApplyConfiguration{}
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *PlacementRequestStatusApplyConfiguration) WithResult(value schedulingv1alpha2.PlacementRequestResult) *PlacementRequestStatusApplyConfiguration {
	b.Result = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PlacementRequestStatusApplyConfiguration) WithReason(value string) *PlacementRequestStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PlacementRequestStatusApplyConfiguration) WithMessage(value string) *PlacementRequestStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithBindings adds the given value to the Bindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bindings field.
func (b *PlacementRequestStatusApplyConfiguration) WithBindings(values ...*PlacementRequestBindingResultApplyConfiguration) *PlacementRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBindings")
		}
		b.Bindings = append(b.Bindings, *values[i])
	}
	return b
}
