/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// PlacementRequestSpecApplyConfiguration represents a declarative configuration of the PlacementRequestSpec type for use
// with apply.
type PlacementRequestSpecApplyConfiguration struct {
	Policy        *schedulingv1alpha2.PlacementRequestPolicy   `json:"policy,omitempty"`
	Priority      *schedulingv1alpha2.PlacementRequestPriority `json:"priority,omitempty"`
	SchedulerName *string                                      `json:"schedulerName,omitempty"`
	Bindings      []v1.BindingApplyConfiguration               `json:"bindings,omitempty"`
}

// PlacementRequestSpecApplyConfiguration constructs a declarative configuration of the PlacementRequestSpec type for use with
// apply.
func PlacementRequestSpec() *PlacementRequestSpecApplyConfiguration {
	return &PlacementRequestSpecApplyConfiguration{}
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *PlacementRequestSpecApplyConfiguration) WithPolicy(value schedulingv1alpha2.PlacementRequestPolicy) *PlacementRequestSpecApplyConfiguration {
	b.Policy = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *PlacementRequestSpecApplyConfiguration) WithPriority(value schedulingv1alpha2.PlacementRequestPriority) *PlacementRequestSpecApplyConfiguration {
	b.Priority = &value
	return b
}

// WithSchedulerName sets the SchedulerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulerName field is set to the value of the last call.
func (b *PlacementRequestSpecApplyConfiguration) WithSchedulerName(value string) *PlacementRequestSpecApplyConfiguration {
	b.SchedulerName = &value
	return b
}

// WithBindings adds the given value to the Bindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bindings field.
func (b *PlacementRequestSpecApplyConfiguration) WithBindings(values ...*v1.BindingApplyConfiguration) *PlacementRequestSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBindings")
		}
		b.Bindings = append(b.Bindings, *values[i])
	}
	return b
}
