/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha2

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-codegen.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_PlacementRequest = map[string]string{
	"": "PlacementRequest is a pod placement request sent to the placement request controller by a scheduler.",
}

func (PlacementRequest) SwaggerDoc() map[string]string {
	return map_PlacementRequest
}

var map_PlacementRequestBindingResult = map[string]string{
	"": "PlacementRequestBindingResult holds the result of a single binding inside a PlacementRequest object. Each binding in the spec is represented by a result and the ObjectMeta is expected to match.",
}

func (PlacementRequestBindingResult) SwaggerDoc() map[string]string {
	return map_PlacementRequestBindingResult
}

var map_PlacementRequestList = map[string]string{
	"":         "PlacementRequestList is a collection of placement requests.",
	"metadata": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
	"items":    "List of placement requests. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller",
}

func (PlacementRequestList) SwaggerDoc() map[string]string {
	return map_PlacementRequestList
}

var map_PlacementRequestSpec = map[string]string{
	"":              "PlacementRequestSpec holds the desired state for a placement request, indicating its policy and also a group of bindings.",
	"policy":        "Policy indicates the relationship between the bindings in a placement request.",
	"priority":      "Priority is an arbitrary integer, placement requests with a higher priority are served first when processing the scheduler queue.",
	"schedulerName": "SchedulerName is the name of the scheduler that is responsible for creating this placement request. This is used to identify the queue that the placement request belongs to.",
	"bindings":      "Bingings is a list of bindings that the scheduler wants to have processed by the placement request controller. Each binding contains a pod and a node name, the controller will try to bind the pod to the node.",
}

func (PlacementRequestSpec) SwaggerDoc() map[string]string {
	return map_PlacementRequestSpec
}

var map_PlacementRequestStatus = map[string]string{
	"":         "PlacementRequestStatus holds the status for a PlacementRequest, it contains the current phase of the binding process, the actual result once the binding has finished, a reason and, in case of failure a user readable message. It also contains a list of individual bindings that correspond to the list provided on the spec, each individual binding may contain its own result.",
	"result":   "Result indicates the overall result of the placement request.",
	"reason":   "Reason is a short, machine-readable string indicating the reason for the result of the placement request.",
	"message":  "Message is a human-readable message indicating the reason for the result of the placement request. This is intended to be used for debugging purposes and should not be used for machine processing.",
	"bindings": "Bindings is a list of individual binding results that correspond to the bindings provided in the spec. Each binding result contains the result of the binding, a reason and a message. The ObjectMeta of each binding result is expected to match the ObjectMeta of the corresponding binding in the spec.",
}

func (PlacementRequestStatus) SwaggerDoc() map[string]string {
	return map_PlacementRequestStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
