/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PlacementRequestLister helps list PlacementRequests.
// All objects returned here must be treated as read-only.
type PlacementRequestLister interface {
	// List lists all PlacementRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.PlacementRequest, err error)
	// PlacementRequests returns an object that can list and get PlacementRequests.
	PlacementRequests(namespace string) PlacementRequestNamespaceLister
	PlacementRequestListerExpansion
}

// placementRequestLister implements the PlacementRequestLister interface.
type placementRequestLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.PlacementRequest]
}

// NewPlacementRequestLister returns a new PlacementRequestLister.
func NewPlacementRequestLister(indexer cache.Indexer) PlacementRequestLister {
	return &placementRequestLister{listers.New[*schedulingv1alpha2.PlacementRequest](indexer, schedulingv1alpha2.Resource("placementrequest"))}
}

// PlacementRequests returns an object that can list and get PlacementRequests.
func (s *placementRequestLister) PlacementRequests(namespace string) PlacementRequestNamespaceLister {
	return placementRequestNamespaceLister{listers.NewNamespaced[*schedulingv1alpha2.PlacementRequest](s.ResourceIndexer, namespace)}
}

// PlacementRequestNamespaceLister helps list and get PlacementRequests.
// All objects returned here must be treated as read-only.
type PlacementRequestNamespaceLister interface {
	// List lists all PlacementRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1alpha2.PlacementRequest, err error)
	// Get retrieves the PlacementRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1alpha2.PlacementRequest, error)
	PlacementRequestNamespaceListerExpansion
}

// placementRequestNamespaceLister implements the PlacementRequestNamespaceLister
// interface.
type placementRequestNamespaceLister struct {
	listers.ResourceIndexer[*schedulingv1alpha2.PlacementRequest]
}
