//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	schedulingv1alpha2 "k8s.io/api/scheduling/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	scheduling "k8s.io/kubernetes/pkg/apis/scheduling"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*schedulingv1alpha2.PlacementRequest)(nil), (*scheduling.PlacementRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PlacementRequest_To_scheduling_PlacementRequest(a.(*schedulingv1alpha2.PlacementRequest), b.(*scheduling.PlacementRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*scheduling.PlacementRequest)(nil), (*schedulingv1alpha2.PlacementRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_scheduling_PlacementRequest_To_v1alpha2_PlacementRequest(a.(*scheduling.PlacementRequest), b.(*schedulingv1alpha2.PlacementRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*schedulingv1alpha2.PlacementRequestBindingResult)(nil), (*scheduling.PlacementRequestBindingResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PlacementRequestBindingResult_To_scheduling_PlacementRequestBindingResult(a.(*schedulingv1alpha2.PlacementRequestBindingResult), b.(*scheduling.PlacementRequestBindingResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*scheduling.PlacementRequestBindingResult)(nil), (*schedulingv1alpha2.PlacementRequestBindingResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_scheduling_PlacementRequestBindingResult_To_v1alpha2_PlacementRequestBindingResult(a.(*scheduling.PlacementRequestBindingResult), b.(*schedulingv1alpha2.PlacementRequestBindingResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*schedulingv1alpha2.PlacementRequestList)(nil), (*scheduling.PlacementRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PlacementRequestList_To_scheduling_PlacementRequestList(a.(*schedulingv1alpha2.PlacementRequestList), b.(*scheduling.PlacementRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*scheduling.PlacementRequestList)(nil), (*schedulingv1alpha2.PlacementRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_scheduling_PlacementRequestList_To_v1alpha2_PlacementRequestList(a.(*scheduling.PlacementRequestList), b.(*schedulingv1alpha2.PlacementRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*schedulingv1alpha2.PlacementRequestSpec)(nil), (*scheduling.PlacementRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec(a.(*schedulingv1alpha2.PlacementRequestSpec), b.(*scheduling.PlacementRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*scheduling.PlacementRequestSpec)(nil), (*schedulingv1alpha2.PlacementRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec(a.(*scheduling.PlacementRequestSpec), b.(*schedulingv1alpha2.PlacementRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*schedulingv1alpha2.PlacementRequestStatus)(nil), (*scheduling.PlacementRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus(a.(*schedulingv1alpha2.PlacementRequestStatus), b.(*scheduling.PlacementRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*scheduling.PlacementRequestStatus)(nil), (*schedulingv1alpha2.PlacementRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus(a.(*scheduling.PlacementRequestStatus), b.(*schedulingv1alpha2.PlacementRequestStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_PlacementRequest_To_scheduling_PlacementRequest(in *schedulingv1alpha2.PlacementRequest, out *scheduling.PlacementRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_PlacementRequest_To_scheduling_PlacementRequest is an autogenerated conversion function.
func Convert_v1alpha2_PlacementRequest_To_scheduling_PlacementRequest(in *schedulingv1alpha2.PlacementRequest, out *scheduling.PlacementRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_PlacementRequest_To_scheduling_PlacementRequest(in, out, s)
}

func autoConvert_scheduling_PlacementRequest_To_v1alpha2_PlacementRequest(in *scheduling.PlacementRequest, out *schedulingv1alpha2.PlacementRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_scheduling_PlacementRequest_To_v1alpha2_PlacementRequest is an autogenerated conversion function.
func Convert_scheduling_PlacementRequest_To_v1alpha2_PlacementRequest(in *scheduling.PlacementRequest, out *schedulingv1alpha2.PlacementRequest, s conversion.Scope) error {
	return autoConvert_scheduling_PlacementRequest_To_v1alpha2_PlacementRequest(in, out, s)
}

func autoConvert_v1alpha2_PlacementRequestBindingResult_To_scheduling_PlacementRequestBindingResult(in *schedulingv1alpha2.PlacementRequestBindingResult, out *scheduling.PlacementRequestBindingResult, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Result = scheduling.PlacementRequestResult(in.Result)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha2_PlacementRequestBindingResult_To_scheduling_PlacementRequestBindingResult is an autogenerated conversion function.
func Convert_v1alpha2_PlacementRequestBindingResult_To_scheduling_PlacementRequestBindingResult(in *schedulingv1alpha2.PlacementRequestBindingResult, out *scheduling.PlacementRequestBindingResult, s conversion.Scope) error {
	return autoConvert_v1alpha2_PlacementRequestBindingResult_To_scheduling_PlacementRequestBindingResult(in, out, s)
}

func autoConvert_scheduling_PlacementRequestBindingResult_To_v1alpha2_PlacementRequestBindingResult(in *scheduling.PlacementRequestBindingResult, out *schedulingv1alpha2.PlacementRequestBindingResult, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Result = schedulingv1alpha2.PlacementRequestResult(in.Result)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_scheduling_PlacementRequestBindingResult_To_v1alpha2_PlacementRequestBindingResult is an autogenerated conversion function.
func Convert_scheduling_PlacementRequestBindingResult_To_v1alpha2_PlacementRequestBindingResult(in *scheduling.PlacementRequestBindingResult, out *schedulingv1alpha2.PlacementRequestBindingResult, s conversion.Scope) error {
	return autoConvert_scheduling_PlacementRequestBindingResult_To_v1alpha2_PlacementRequestBindingResult(in, out, s)
}

func autoConvert_v1alpha2_PlacementRequestList_To_scheduling_PlacementRequestList(in *schedulingv1alpha2.PlacementRequestList, out *scheduling.PlacementRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]scheduling.PlacementRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_PlacementRequestList_To_scheduling_PlacementRequestList is an autogenerated conversion function.
func Convert_v1alpha2_PlacementRequestList_To_scheduling_PlacementRequestList(in *schedulingv1alpha2.PlacementRequestList, out *scheduling.PlacementRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha2_PlacementRequestList_To_scheduling_PlacementRequestList(in, out, s)
}

func autoConvert_scheduling_PlacementRequestList_To_v1alpha2_PlacementRequestList(in *scheduling.PlacementRequestList, out *schedulingv1alpha2.PlacementRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]schedulingv1alpha2.PlacementRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_scheduling_PlacementRequestList_To_v1alpha2_PlacementRequestList is an autogenerated conversion function.
func Convert_scheduling_PlacementRequestList_To_v1alpha2_PlacementRequestList(in *scheduling.PlacementRequestList, out *schedulingv1alpha2.PlacementRequestList, s conversion.Scope) error {
	return autoConvert_scheduling_PlacementRequestList_To_v1alpha2_PlacementRequestList(in, out, s)
}

func autoConvert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec(in *schedulingv1alpha2.PlacementRequestSpec, out *scheduling.PlacementRequestSpec, s conversion.Scope) error {
	out.Policy = scheduling.PlacementRequestPolicy(in.Policy)
	out.Priority = scheduling.PlacementRequestPriority(in.Priority)
	out.SchedulerName = in.SchedulerName
	out.Bindings = *(*[]v1.Binding)(unsafe.Pointer(&in.Bindings))
	return nil
}

// Convert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec is an autogenerated conversion function.
func Convert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec(in *schedulingv1alpha2.PlacementRequestSpec, out *scheduling.PlacementRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_PlacementRequestSpec_To_scheduling_PlacementRequestSpec(in, out, s)
}

func autoConvert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec(in *scheduling.PlacementRequestSpec, out *schedulingv1alpha2.PlacementRequestSpec, s conversion.Scope) error {
	out.Policy = schedulingv1alpha2.PlacementRequestPolicy(in.Policy)
	out.Priority = schedulingv1alpha2.PlacementRequestPriority(in.Priority)
	out.SchedulerName = in.SchedulerName
	out.Bindings = *(*[]v1.Binding)(unsafe.Pointer(&in.Bindings))
	return nil
}

// Convert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec is an autogenerated conversion function.
func Convert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec(in *scheduling.PlacementRequestSpec, out *schedulingv1alpha2.PlacementRequestSpec, s conversion.Scope) error {
	return autoConvert_scheduling_PlacementRequestSpec_To_v1alpha2_PlacementRequestSpec(in, out, s)
}

func autoConvert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus(in *schedulingv1alpha2.PlacementRequestStatus, out *scheduling.PlacementRequestStatus, s conversion.Scope) error {
	out.Result = scheduling.PlacementRequestResult(in.Result)
	out.Reason = in.Reason
	out.Message = in.Message
	out.Bindings = *(*[]scheduling.PlacementRequestBindingResult)(unsafe.Pointer(&in.Bindings))
	return nil
}

// Convert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus is an autogenerated conversion function.
func Convert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus(in *schedulingv1alpha2.PlacementRequestStatus, out *scheduling.PlacementRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_PlacementRequestStatus_To_scheduling_PlacementRequestStatus(in, out, s)
}

func autoConvert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus(in *scheduling.PlacementRequestStatus, out *schedulingv1alpha2.PlacementRequestStatus, s conversion.Scope) error {
	out.Result = schedulingv1alpha2.PlacementRequestResult(in.Result)
	out.Reason = in.Reason
	out.Message = in.Message
	out.Bindings = *(*[]schedulingv1alpha2.PlacementRequestBindingResult)(unsafe.Pointer(&in.Bindings))
	return nil
}

// Convert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus is an autogenerated conversion function.
func Convert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus(in *scheduling.PlacementRequestStatus, out *schedulingv1alpha2.PlacementRequestStatus, s conversion.Scope) error {
	return autoConvert_scheduling_PlacementRequestStatus_To_v1alpha2_PlacementRequestStatus(in, out, s)
}
